http:
  routers:
    keycloak-http:
      rule: "Host(`{{ inventory_hostname }}`)"
      entryPoints:
        - http
        - https
      middlewares:
      service: "keycloak"
    keycloak-https:
      rule: "Host(`{{ inventory_hostname }}`)"
      entryPoints:
        - http
        - https
      middlewares:
      service: "keycloak"
      tls: {}
  services:
    keycloak:
      loadBalancer:
        healthCheck:
          path: /auth/realms/master
          interval: "10s"
          timeout: "3s"
        servers:
{% for host in groups.keycloak %}
        - url: "http://{{ host }}:8080"
{% endfor %}
        # Sticky session is required for users to login
        sticky:
          cookie: {}
