http:
  routers:
    keycloak-http:
      rule: "Host(`lb.itix.lab`)"
      entryPoints:
        - http
        - https
      middlewares:
      service: "keycloak"
    keycloak-https:
      rule: "Host(`lb.itix.lab`)"
      entryPoints:
        - http
        - https
      middlewares:
      service: "keycloak"
      tls: {}
  services:
    keycloak:
      loadBalancer:
        healthCheck:
          path: /auth/realms/master
          interval: "10s"
          timeout: "3s"
        servers:
        - url: "http://sso1.itix.lab:8080"
        - url: "http://sso2.itix.lab:8080"
        - url: "http://sso3.itix.lab:8080"
        # Sticky session is required for users to login
        sticky:
          cookie: {}
