log:
  level: "INFO"

accesslog: true

providers:
  file:
    directory: /opt/traefik/etc/conf.d/
    watch: true

global:
  sendanonymoususage: false
  checknewversion: false

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
